
# Generated by CodiumAI
from src.main import ordenamientoBurbuja


import pytest

class TestOrdenamientoburbuja:
    
    @pytest.mark.parametrize(
            "input, expected",
            [
                ([4, 2, 1, 3], [1, 2, 3, 4]),
                ([4, 2, 1, 3], [1, 2, 3, 4]),
                ([], []),
                ([1], [1]),
                ([2, 1], [1, 2]),
                (["Pepe", "Alvaro"], ["Alvaro", "Pepe"])
            ]
    )
    # Test del funcionamiento del algoritmo.
    def test_sort_ascending_order(self, input, expected):

        # Assert
        assert ordenamientoBurbuja(input) == expected